2024-10-24 18:47:33,299 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Urban\01\tests_12_4.py", line 18, in test_run
    r2 = Runner(2)
         ^^^^^^^^^
  File "C:\Urban\01\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-24 18:47:33,305 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Urban\01\tests_12_4.py", line 9, in test_walk
    r1 = Runner('Вася', -5)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Urban\01\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
